### PR TITLE
Added missing "mediapipe" dependency for mediapipe_face_common.py

### PR DESCRIPTION
**Pull request by Ambrosiussen**
See: https://github.com/patrickvonplaten/controlnet_aux/blob/f31dbd95cf7426164d0d0f88fe7339afcfbcb668/src/controlnet_aux/mediapipe_face/mediapipe_face_common.py#LL3C1-L3C1

### CODE REVIEW

**Comment by jinwonkim93** [comment]
Check https://github.com/patrickvonplaten/controlnet_aux/pull/29. Did not include on setup because it might cause protobuf conflict

**Comment by Ambrosiussen** [comment]
But then why is it part of ControlNet AUX if it doesnt work??

**Comment by jinwonkim93** [comment]
You can install it seperately by `pip install mediapipe`

**Comment by Ambrosiussen** [comment]
Yes, I did that locally. But generally bad practice to ship code that needs a dependency not provided in a requirements.txt or setup. Maybe try to catch the exception when instantiating a mediapipe_face with the instructions on installing the missing dependency? (Or even better, add a requirements.txt)

**Comment by patrickvonplaten** [comment]
Ideally we would throw a warning if mediapipe control is imported but `mediapipe` is not installed. Would be happy if we can not explode the dependency tree of this package

**Comment by Ambrosiussen** [comment]
@patrickvonplaten Thoughts on adjusted code?

**Comment by patrickvonplaten** [comment]
Perfect! Thanks!

**Pull request merged**
