### PR TITLE
feat: support for load weights from local dir

### PR DESCRIPTION
**Pull request by CrazyBoyM**

### CODE REVIEW

**Comment by CrazyBoyM** [comment]
image

test well on my env.  
here is my test code:
```
from PIL import Image
import requests
from io import BytesIO
from controlnet_aux import HEDdetector, MidasDetector, MLSDdetector, OpenposeDetector, PidiNetDetector, NormalBaeDetector, LineartDetector, LineartAnimeDetector, CannyDetector, ContentShuffleDetector, ZoeDetector

# load image
url = "https://image.netfrp.com/uploads/639320479a385.png"

response = requests.get(url)
img = Image.open(BytesIO(response.content)).convert("RGB").resize((512, 512))

# load checkpoints
hed = HEDdetector.from_pretrained("/mywork/cond-models/Annotators")
midas = MidasDetector.from_pretrained("/mywork/cond-models/Annotators")
mlsd = MLSDdetector.from_pretrained("/mywork/cond-models/Annotators")
open_pose = OpenposeDetector.from_pretrained("/mywork/cond-models/Annotators")
pidi = PidiNetDetector.from_pretrained("/mywork/cond-models/Annotators")
normal_bae = NormalBaeDetector.from_pretrained("/mywork/cond-models/Annotators")
lineart = LineartDetector.from_pretrained("/mywork/cond-models/Annotators")
lineart_anime = LineartAnimeDetector.from_pretrained("/mywork/cond-models/Annotators")
zoe = ZoeDetector.from_pretrained("/mywork/cond-models/Annotators")

# instantiate
canny = CannyDetector()
content = ContentShuffleDetector()


# process
processed_image_hed = hed(img)
processed_image_midas = midas(img)
processed_image_mlsd = mlsd(img)
processed_image_open_pose = open_pose(img, hand_and_face=True)
processed_image_pidi = pidi(img, safe=True)
processed_image_normal_bae = normal_bae(img)
processed_image_lineart = lineart(img, coarse=True)
processed_image_lineart_anime = lineart_anime(img)
processed_image_zoe = zoe(img)

processed_image_canny = canny(img)
processed_image_content = content(img)

# save
processed_image_hed.save("hed.png")
processed_image_midas.save("midas.png")
processed_image_mlsd.save("mlsd.png")
processed_image_open_pose.save("open_pose.png")
processed_image_pidi.save("pidi.png")
processed_image_normal_bae.save("normal_bae.png")
processed_image_lineart.save("lineart.png")
processed_image_lineart_anime.save("lineart_anime.png")
processed_image_zoe.save("zoe.png")
processed_image_canny.save("canny.png")
processed_image_content.save("content.png")
```

**Comment by jinwonkim93** [comment]
Hi just saw your code. what about using cache_dir in hf_hub_download [link](https://github.com/huggingface/huggingface_hub/blob/f9563a3d72302d79fac8cff0dff23f90bd388186/src/huggingface_hub/file_download.py#L953rl)

**Comment by jinwonkim93** [comment]
> > Hi just saw your code. what about using cache_dir in hf_hub_download [link](https://github.com/huggingface/huggingface_hub/blob/f9563a3d72302d79fac8cff0dff23f90bd388186/src/huggingface_hub/file_download.py#L953rl) by adding args in from_pretrained
> 
> happy to try it, does the cache_dir has a same as local dir? such as:
> 
> ```
> local_dir
> - weight1.pth
> - weight2.pth
> - weight3.bin
> ```
> 
> not as:
> 
> ```
> cache_dir
> - blob
> - refs
> - ...
> ```

oh so the purpose is to support different weights in one folder. how about converting weights to hf_hub format? Then you don't have to change code.
```
weights
|-- weight1
|--|-- blob
|--|-- refs
|-- weight2
|--|-- blob
|--|-- refs

**Comment by CrazyBoyM** [comment]
> > > Hi just saw your code. what about using cache_dir in hf_hub_download [link](https://github.com/huggingface/huggingface_hub/blob/f9563a3d72302d79fac8cff0dff23f90bd388186/src/huggingface_hub/file_download.py#L953rl) by adding args in from_pretrained
> > 
> > 
> > happy to try it, does the cache_dir has a same as local dir? such as:
> > ```
> > local_dir
> > - weight1.pth
> > - weight2.pth
> > - weight3.bin
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > not as:
> > ```
> > cache_dir
> > - blob
> > - refs
> > - ...
> > ```
> 
> oh so the purpose is to support different weights in one folder. how about converting weights to hf_hub format? Then you don't have to change code.
> 
> ```
> weights
> |-- weight1
> |--|-- blob
> |--|-- refs
> |-- weight2
> |--|-- blob
> |--|-- refs
> ```

I just want to 'git lfs pull' the https://huggingface.co/lllyasviel/Annotators repo and load weights file in the repo manually, for in my country, sometimes it is very slow to use 'hf_hub_download' api to download them, and I don't want to save the full repo's weights in disk cache.So I don't sure if it is necessary to add the code for loading '.bin' or '.pth' weight files from local dir.What do you think about it?

**Comment by CrazyBoyM** [comment]
> > > > > Hi just saw your code. what about using cache_dir in hf_hub_download [link](https://github.com/huggingface/huggingface_hub/blob/f9563a3d72302d79fac8cff0dff23f90bd388186/src/huggingface_hub/file_download.py#L953rl) by adding args in from_pretrained
> > > > 
> > > > 
> > > > happy to try it, does the cache_dir has a same as local dir? such as:
> > > > ```
> > > > local_dir
> > > > - weight1.pth
> > > > - weight2.pth
> > > > - weight3.bin
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > not as:
> > > > ```
> > > > cache_dir
> > > > - blob
> > > > - refs
> > > > - ...
> > > > ```
> > > 
> > > 
> > > oh so the purpose is to support different weights in one folder. how about converting weights to hf_hub format? Then you don't have to change code.
> > > ```
> > > weights
> > > |-- weight1
> > > |--|-- blob
> > > |--|-- refs
> > > |-- weight2
> > > |--|-- blob
> > > |--|-- refs
> > > ```
> > 
> > 
> > I just want to 'git lfs pull' the https://huggingface.co/lllyasviel/Annotators repo and load weights file in the repo manually, for in my country, sometimes it is very slow to use 'hf_hub_download' api to download them, and I don't want to save the full repo's weights in disk cache.So I don't sure if it is necessary to add the code for loading '.bin' or '.pth' weight files from local dir.What do you think about it?
> 
> you can initialize [#3 (comment)](https://github.com/patrickvonplaten/controlnet_aux/issues/3#issuecomment-1480824998) like this.

great! but I have no idea whether to change the code or just close it, can you give me some suggestion?Happy to learn.

**Comment by jinwonkim93** [comment]
> > > > > > Hi just saw your code. what about using cache_dir in hf_hub_download [link](https://github.com/huggingface/huggingface_hub/blob/f9563a3d72302d79fac8cff0dff23f90bd388186/src/huggingface_hub/file_download.py#L953rl) by adding args in from_pretrained
> > > > > 
> > > > > 
> > > > > happy to try it, does the cache_dir has a same as local dir? such as:
> > > > > ```
> > > > > local_dir
> > > > > - weight1.pth
> > > > > - weight2.pth
> > > > > - weight3.bin
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > not as:
> > > > > ```
> > > > > cache_dir
> > > > > - blob
> > > > > - refs
> > > > > - ...
> > > > > ```
> > > > 
> > > > 
> > > > oh so the purpose is to support different weights in one folder. how about converting weights to hf_hub format? Then you don't have to change code.
> > > > ```
> > > > weights
> > > > |-- weight1
> > > > |--|-- blob
> > > > |--|-- refs
> > > > |-- weight2
> > > > |--|-- blob
> > > > |--|-- refs
> > > > ```
> > > 
> > > 
> > > I just want to 'git lfs pull' the https://huggingface.co/lllyasviel/Annotators repo and load weights file in the repo manually, for in my country, sometimes it is very slow to use 'hf_hub_download' api to download them, and I don't want to save the full repo's weights in disk cache.So I don't sure if it is necessary to add the code for loading '.bin' or '.pth' weight files from local dir.What do you think about it?
> > 
> > 
> > you can initialize [#3 (comment)](https://github.com/patrickvonplaten/controlnet_aux/issues/3#issuecomment-1480824998) like this.
> 
> great! but I have no idea whether to change the code or just close it, can you give me some suggestion?Happy to learn.

Since I am not the code owner I think I have no authority to guide you. But since you asked, the intention of your PR is to easily load local weight, but not all detector have the same interface. which may conflict users. how about starting from here?

**Comment by CrazyBoyM** [comment]
> > > > > > > Hi just saw your code. what about using cache_dir in hf_hub_download [link](https://github.com/huggingface/huggingface_hub/blob/f9563a3d72302d79fac8cff0dff23f90bd388186/src/huggingface_hub/file_download.py#L953rl) by adding args in from_pretrained
> > > > > > 
> > > > > > 
> > > > > > happy to try it, does the cache_dir has a same as local dir? such as:
> > > > > > ```
> > > > > > local_dir
> > > > > > - weight1.pth
> > > > > > - weight2.pth
> > > > > > - weight3.bin
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > not as:
> > > > > > ```
> > > > > > cache_dir
> > > > > > - blob
> > > > > > - refs
> > > > > > - ...
> > > > > > ```
> > > > > 
> > > > > 
> > > > > oh so the purpose is to support different weights in one folder. how about converting weights to hf_hub format? Then you don't have to change code.
> > > > > ```
> > > > > weights
> > > > > |-- weight1
> > > > > |--|-- blob
> > > > > |--|-- refs
> > > > > |-- weight2
> > > > > |--|-- blob
> > > > > |--|-- refs
> > > > > ```
> > > > 
> > > > 
> > > > I just want to 'git lfs pull' the https://huggingface.co/lllyasviel/Annotators repo and load weights file in the repo manually, for in my country, sometimes it is very slow to use 'hf_hub_download' api to download them, and I don't want to save the full repo's weights in disk cache.So I don't sure if it is necessary to add the code for loading '.bin' or '.pth' weight files from local dir.What do you think about it?
> > > 
> > > 
> > > you can initialize [#3 (comment)](https://github.com/patrickvonplaten/controlnet_aux/issues/3#issuecomment-1480824998) like this.
> > 
> > 
> > great! but I have no idea whether to change the code or just close it, can you give me some suggestion?Happy to learn.
> 
> Since I am not the code owner I think I have no authority to guide you. But since you asked, the intention of your PR is to easily load local weight, but not all detector have the same interface. which may conflict users. how about starting from here?

I have test all detector on the 0.0.3 version, it just works fine.But maybe there are some easy way to design a api for any detector added in the future, do you have good idea on it?

**Comment by patrickvonplaten** [comment]
I'm actually fully ok with merging this! That's a very similair technique to what we use for `diffusers`: https://github.com/huggingface/diffusers/blob/77bfb562414e93f35b5d6cea8431d5163fe46191/src/diffusers/pipelines/pipeline_utils.py#L883

**Pull request merged**
